CREATE OR REPLACE VIEW V_KINCAID_EMPRESAS_P AS
WITH origin_data AS (
    SELECT
        A.NU9_CCLIEN,
        A.NU9_CLOJA,
        C.NRI_DESC AS ORIGINACAO,
        B.RD0_SIGLA AS PROFISSIONAL_ORIGINACAO,
        A.NU9_PERC AS PERCENTUAL_ORIGINACAO
    FROM PROTHEUS.NU9010 A
    LEFT JOIN PROTHEUS.RD0010 B ON B.RD0_CODIGO = A.NU9_CPART AND B.D_E_L_E_T_ = ' '
    LEFT JOIN PROTHEUS.NRI010 C ON C.NRI_COD = A.NU9_CTIPO AND C.D_E_L_E_T_ = ' '
    WHERE A.D_E_L_E_T_ = ' '
)
SELECT
    SA1.A1_COD || '-' || SA1.A1_LOJA as "codigo_empresa",
    SA1.A1_NOME as "nome_chave",
    SA1.A1_NREDUZ as "razao_social",
    CASE NUH.NUH_PERFIL
      WHEN '1' THEN 'CLIENTE/PAGADOR'
      WHEN '2' THEN 'SOMENTE PAGADOR'
      ELSE 'NAO CLIENTE'
    END as "classe_operacional",
    CASE WHEN SA1.A1_DTCAD = ' ' THEN SA1.A1_DTCAD
      ELSE SUBSTR(SA1.A1_DTCAD,7,2)||'/'||SUBSTR(SA1.A1_DTCAD,5,2)||'/'||SUBSTR(SA1.A1_DTCAD,1,4)
    END AS "data_cadastramento",
    CASE WHEN NUH.NUH__DTVIR = ' ' THEN NUH.NUH__DTVIR
      ELSE SUBSTR(NUH.NUH__DTVIR,7,2)||'/'||SUBSTR(NUH.NUH__DTVIR,5,2)||'/'||SUBSTR(NUH.NUH__DTVIR,1,4)
    END AS "data_cliente",
    RD0.RD0_NOME as "responsavel",
    RD0.RD0_SIGLA as "matr_responsavel",
    ACY.ACY_DESCRI as "grupo_empresas",
    AOV.AOV_DESSEG as "ramo_atividade",
    CASE WHEN SA1.A1_MSBLQL = '1' THEN 'INATIVO' ELSE 'ATIVO' END CLIENTE_SITUACAO,
    CASE WHEN NUH.NUH_SITCLI = '1' THEN 'POTENCIAL' ELSE 'EFETIVO' END CLIENTE_SITIACAO,
    CASE WHEN NUH.NUH_SITCAD = '1' THEN 'PROVISORIO' ELSE 'DEFINITIVO' END CLIENTE_CADASTRO,
    CASE
      WHEN NUH.NUH__PROSP = '1' THEN 'PROSPECT CONVERTIDO'
      WHEN NUH.NUH__PROSP = '2' THEN 'PROSPECT'
      WHEN NUH.NUH__PROSP = '3' THEN 'EX-PROSPECT'
      WHEN NUH.NUH__PROSP = '4' THEN 'EX-CLIENTE'
      WHEN NUH.NUH__PROSP = '5' THEN 'N/A'
    END PROSPECT_CONVERTIDO,
    (SELECT LISTAGG(TRIM(ORIGINACAO), ', ') WITHIN GROUP (ORDER BY ORIGINACAO)
     FROM origin_data od
     WHERE od.NU9_CCLIEN = SA1.A1_COD AND od.NU9_CLOJA = SA1.A1_LOJA) AS "ORIGINACAO",
    (SELECT LISTAGG(TRIM(PROFISSIONAL_ORIGINACAO), ', ') WITHIN GROUP (ORDER BY PROFISSIONAL_ORIGINACAO)
     FROM origin_data od
     WHERE od.NU9_CCLIEN = SA1.A1_COD AND od.NU9_CLOJA = SA1.A1_LOJA) AS "PROFISSIONAL_ORIGINACAO",
    (SELECT LISTAGG(TRIM(PERCENTUAL_ORIGINACAO), '; ') WITHIN GROUP (ORDER BY PERCENTUAL_ORIGINACAO)
     FROM origin_data od
     WHERE od.NU9_CCLIEN = SA1.A1_COD AND od.NU9_CLOJA = SA1.A1_LOJA) AS "PERCENTUAL_ORIGINACAO"
FROM PROTHEUS.SA1010 SA1
LEFT JOIN PROTHEUS.NUH010 NUH ON NUH.NUH_COD = SA1.A1_COD AND NUH.NUH_LOJA = SA1.A1_LOJA AND NUH.D_E_L_E_T_ = ' '
LEFT JOIN PROTHEUS.ACY010 ACY ON SA1.A1_GRPVEN = ACY.ACY_GRPVEN AND ACY.D_E_L_E_T_ = ' '
LEFT JOIN PROTHEUS.AOV010 AOV ON SA1.A1_CODSEG = AOV.AOV_CODSEG AND AOV.D_E_L_E_T_ = ' '
LEFT JOIN PROTHEUS.RD0010 RD0 ON NUH.NUH_CPART = RD0.RD0_CODIGO AND RD0.D_E_L_E_T_ = ' '
LEFT JOIN PROTHEUS.NS7010 NS7 ON NS7.NS7_COD = NUH.NUH_CESCR AND NS7.D_E_L_E_T_ = ' '
ORDER BY "nome_chave";
